modLoader="javafml"
loaderVersion="[45,)"
license="Academic Free License v3.0"

[[mods]]
modId="metaplay"
version="1.1.3.2"
displayName="Metaplay"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://github.com/qgqtyt/"
logoFile="logo.png"
authors="qwerty_gaming"

[[dependencies.metaplay]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.4]"
    ordering="NONE"
    side="BOTH"




